/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tSRQ9C37d7z
 */
import { Button } from "@/components/ui/button"
import { DialogTrigger, DialogTitle, DialogDescription, DialogHeader, DialogContent, Dialog } from "@/components/ui/dialog"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { SelectValue, SelectTrigger, SelectContent, Select, SelectItem } from "@/components/ui/select"

export function AddNotificationModal() {
  const numbers = Array.from({ length: 23 }, (_, index) => index + 1)

  const SelectItem = ({ value, children }: { value: string | number, children: React.ReactNode }) => (
      <option value={value}>{children}</option>
  );

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline">Open Modal</Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[425px]">
        <DialogHeader>
          <DialogTitle>Modal Title</DialogTitle>
          <DialogDescription>Enter your information in the modal.</DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          <div className="space-y-2">
            <Label htmlFor="input1">Input 1</Label>
            <div className="flex gap-2">
              <Input className="w-3/4" id="input1" placeholder="Enter input 1" />
              <Button>Button</Button>
            </div>
          </div>
          <div className="space-y-2">
            <Label htmlFor="input2">Input 2</Label>
            <Input id="input2" placeholder="Enter input 2" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="input3">Input 3</Label>
            <Select>
              <SelectTrigger>
                <SelectValue>Select an option</SelectValue>
              </SelectTrigger>
              <SelectContent>
                {numbers.map(value => <SelectItem value={value}>{value} 시</SelectItem>)}
              </SelectContent>
            </Select>
          </div>
          <Button className="w-full" type="submit">
            Submit
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  )
}
